  variable "subnet_name" {}
  variable "virtual_network_name" {}
  variable "resource_group_name" {}
  variable "pip_name" {}
  variable "location" {}
  variable "nic_name" {}
  variable "todo_VM_name" {}
 variable "VM_username" {}
  variable "VM_password" {}